"""Pinned upstream semantic surface -> local gates, never an execution oracle.

`cpu_subset` means evidence exists for particular fixtures, NOT all programs.
Missing capabilities remain explicit rows instead of disappearing from totals.
Coverage of API/IR names is mechanically checked; behavioral completeness is not.
"""
from workspace_paths import RESULTS

DACAPO_COMMIT = "4616402710f39df3e5f5bd7930a6c036025aaac3"
BASELINE_COUNTS = {"model_families": 8, "fx_operator_kinds": 6, "dsl_primitive_kinds": 3}
TARGET_COUNTS = {"model_families": 16, "fx_operator_kinds": 12}
# Baseline FX kinds: add, multiply, square, power(2/4), linear, flatten.
# Python aliases / overload signatures / tensor sizes do not increase counts.
# DSL kinds: +, *, rotate; ciphertext/plaintext overloads are not separate kinds.


def row(status, tests, note):
    return dict(status=status, tests=tests, note=note, poseidon_gpu="not_validated")


SEMANTICS = {
    "add": row("cpu_subset", ["test_hecate_contract.HecateContractTests.test_valid_affine_and_no_execution_claim"],
               "cipher+cipher or cipher+public; generated fragment requires cipher on left"),
    "multiply": row("cpu_subset", ["test_hecate_contract.HecateContractTests.test_cipher_product_and_multi_cipher_return"],
                    "cipher*cipher includes SEAL relinearization; cipher*public also verified"),
    "subtract": row("native_v1_cpu_fixture", ["test_native_arithmetic.NativeArithmeticTests.test_v1_cipher_negation_subtraction_and_public_subtraction",
                    "test_native_arithmetic.NativeArithmeticEvidenceTests.test_native_cipher_subtract_real",
                    "test_native_arithmetic.NativeArithmeticEvidenceTests.test_swapped_subtraction_detected_after_decryption"],
                    "schema-2 selects v1 native cipher-cipher/public subtraction; v0 unchanged; local frontend constant-fold fix required"),
    "negate": row("native_v1_cpu_fixture", ["test_native_arithmetic.NativeArithmeticTests.test_v1_cipher_negation_subtraction_and_public_subtraction",
                  "test_native_arithmetic.NativeArithmeticEvidenceTests.test_native_negate_and_plain_subtract_real"],
                  "v1 permits -cipher, dispatched to real Hecate __neg__; v0 still rejects native unary syntax"),
    "rotation": row("v2_cpu_subset", ["test_rotation_contract.RotationContractTests.test_v2_steps_and_legacy_rejection",
                    "test_rotation_contract.RotationEncryptedEvidenceTests.test_all_six_rotations_and_wrong_direction_real",
                    "test_rotation_contract.RotationEncryptedEvidenceTests.test_actual_missing_key_probe"],
                    "v2 signed steps +/-1,+/-2,+/-3; actual key files verified before VM execution; period4 layout only, v0/v1 unchanged"),
    "bootstrap": row("forbidden_backend_gap", ["test_hecate_contract.HecateContractTests.test_call_and_attribute_allowlist",
                     "test_bootstrap_frontend.BootstrapFrontendTests",
                     "test_bootstrap_frontend.BootstrapFrontendEvidenceTests"],
                     "local frontend container writeback fix has actual Earth IR dataflow/verification evidence for Expr/list/tuple/object ndarray including zero-dimensional and matrix storage; no real bootstrap backend execution, no Agent permission; SEAL runtime simulation is never acceptable FHE evidence"),
    "function_io": row("multi_input_candidate_pipeline_cpu_subset", ["test_hecate_contract.HecateContractTests.test_signature_and_result_count",
                       "test_multi_input.MultiInputTests.test_all_golden_signatures_and_no_legacy_relaxation",
                       "test_multi_input.MultiInputEvidenceTests.test_real_arity_metadata_immutability_and_counterexample",
                       "test_schema3_graph.Schema3EvidenceTests.test_actual_candidate_sandbox_multi_input_and_negative",
                       "test_agent_lineage_audit.RealLineageEvidenceTests.test_saved_outputs_artifacts_and_cumulative_coverage"],
                       "schema3/v3 AST verifies 2..4 encrypted inputs; v4 request clarifies unchanged grammar; cumulative CPU cohort covers two inputs and six-case DeepSeek Flash cohort verifies live 3/4-input generation; legacy single input unchanged"),
    "function_call": row("native_core_opt_in_live_agent_eleven_feature_cpu_subset", [
                         "test_hecate_contract.HecateContractTests.test_call_and_attribute_allowlist",
                         "test_native_function_calls.NativeFunctionTests",
                         "test_native_function_evidence.NativeCallEvidenceTests",
                         "test_native_agent_contract.NativeAgentContractTests",
                         "test_checked_native_evidence.CheckedNativeEvidenceTests",
                         "test_native_function_exercises.NativeExerciseTests",
                         "test_native_exercise_evidence.NativeExerciseEvidenceTests",
                         "test_native_function_paid_evidence.NativeFunctionPaidEvidenceTests",
                         "test_native_array_core.NativeArrayTests",
                         "test_native_array_evidence.NativeArrayEvidenceTests",
                         "test_native_array_exercises.NativeArrayExerciseTests",
                         "test_native_array_exercise_evidence.NativeArrayManualEvidenceTests",
                         "test_native_starred.NativeStarredTests",
                         "test_native_starred.NativeStarredFrontendTests",
                         "test_native_starred_evidence.NativeStarredEvidenceTests",
                         "test_native_array_arithmetic.NativeArrayArithmeticTests",
                         "test_native_array_arithmetic.NativeArrayArithmeticFrontendTests",
                         "test_native_array_arithmetic_evidence.NativeArrayArithmeticEvidenceTests",
                         "test_native_public_loops.NativeLoopTests",
                         "test_native_public_loops.NativeLoopFrontendTests",
                         "test_native_loop_evidence.NativeLoopEvidenceTests"],
                         "local native createCall statically clones verified single-block IR; native core is an explicit opt-in Agent contract, not a union with v22; eleven live Agent cases passed real SEAL CPU differential tests (176 values), ten first-pass and one repaired; ten call features have finite output influence and empty return has trace-structural evidence bound to actual native call sites; separate native-array v3 request supports bounded readonly object-array returns with ten manual positives and one detected wrong-transpose counterexample, but no live Agent array coverage yet; recursion rejected; not full DSL coverage"),
    "public_constant": row("cpu_subset", ["test_hecate_contract.HecateContractTests.test_no_plain_outputs_or_unchecked_broadcast"],
                           "bounded finite real scalar/length1/length4 registry; matrix rows lowered by frontend"),
    "save_trace": row("trusted_harness", ["test_candidate_pipeline.CandidateContractTests.test_ast_evaluation_dispatch_without_exec"],
                      "harness owns hc.save and output paths; Agent cannot write files"),
    "mutation": row("native_array_alias_cpu_subset", [
                    "test_hecate_contract.HecateContractTests.test_no_control_flow_mutation_or_augmented_assignment",
                    "test_native_scalar_augmented.NativeScalarAugmentedTests",
                    "test_native_scalar_augmented.NativeScalarAugmentedFrontendTests",
                    "test_native_augmented_evidence.NativeAugmentedEvidenceTests",
                    "test_native_array_mutation.NativeArrayMutationTests",
                    "test_native_array_mutation.NativeArrayMutationFrontendTests",
                    "test_native_array_mutation_evidence.NativeArrayMutationEvidenceTests"],
                    "native request v9 scalar Expr rebinding remains unchanged; opt-in v10 also permits ndarray name-target +=/-=/*= with alias-aware c/p cell transitions, views/copies, overlapping operands and order-K layout; thirteen manual encrypted positives and two numerical counterexamples; subscript/attribute writes remain rejected; no live Agent v9/v10 evidence"),
    "empty_accumulator": row("rejected_unverified", ["test_hecate_contract.HecateContractTests.test_call_and_attribute_allowlist"],
                             "upstream Empty helper exists; not accepted as a generator operation"),
    "control_flow": row("rejected_unverified", ["test_hecate_contract.HecateContractTests.test_no_control_flow_mutation_or_augmented_assignment"],
                        "upstream Python loops execute while tracing; not encrypted data-dependent branching"),
    "shape_layout": row("cpu_subset", ["test_model_graph.GraphContractTests.test_reject_cipher_layout_merge",
                        "test_chunked_model.ChunkedModelTests",
                        "test_chunked_model_evidence.ChunkedEvidenceTests",
                        "test_logical_reshape.ReshapeTests",
                        "test_logical_reshape_evidence.LogicalReshapeEvidenceTests",
                        "test_logical_reshape_paid.LogicalReshapePaidTests"],
                        "legacy bounded C-order reshape: rank1..4, product<=8, one inferred dimension, no permutation; separate schema4 explicitly partitions one 5..16-element rank1..4 logical input into 2..4 period4 ciphertexts, with tail zero padding and cross-chunk Linear reductions; not arbitrary tensor/batch/Conv support"),
    "broadcast": row("cpu_subset", ["test_model_graph.GraphContractTests.test_reject_bad_linear_and_broadcast",
                     "test_wide_linear.WideLinearRuleEvidenceTests.test_all_hidden_widths_real_encrypted_execution"],
                     "scalar/length1 or exact logical vector only, including width5..8 scalar-neuron vectors; no arbitrary multidimensional broadcast"),
    "rescale": row("compiler_owned_cpu_subset", ["test_seal_cpu_golden"],
                   "SEAL profile removes one 60-bit physical prime; GPU mapping remains separate"),
    "modswitch": row("compiler_owned_cpu_subset", ["test_seal_cpu_golden",
                     "test_modswitch_semantics.ModswitchEvidenceTests.test_all_physical_q_prefixes_aliases_scale_and_decode",
                     "test_modswitch_semantics.ModswitchEvidenceTests.test_hashes_and_native_success_without_gpu_claim",
                     "test_static_plan_conventions.StaticPlanConventionEvidenceTests.test_native_plan_output_and_source_snapshots",
                     "test_poseidon_cohort_preflight.CohortPreflightEvidenceTests.test_all_96_real_artifacts_blocked_at_modswitch_with_no_schedule"],
                     "SEAL drops explicit positive count; Poseidon CPU prefix/scale semantics and explicit constant-level selection through static-plan preparation verified; HEVM opcode4/GPU execution still rejected"),
    "upscale": row("forbidden_backend_gap", ["test_seal_cpu_golden"],
                   "HEVM opcode5 rejected before native execution"),
    "schedule": row("compiler_owned_cpu_subset", ["test_native_compiler_artifacts"],
                    "Earth apply_schedule is compiler representation, not an Agent statement"),
    "relinearization": row("compiler_owned_cpu_subset", ["test_seal_cpu_golden"],
                           "SEAL MulCC performs relinearize; Poseidon GPU multiply contract not yet aligned"),
    "keys_security": row("cpu_subset", ["test_seal_cpu_golden"],
                         "unchanged tc128 SEAL N32768, key generation and key storage owned by harness"),
    "polynomial": row("cpu_subset", ["test_fx_to_hecate.FXTranslatorTests.test_all_catalog_plaintext_semantics_and_exact_state_reproducibility",
                      "test_explicit_power.PowerContractTests.test_closed_form_and_reject_unsupported_exponents",
                      "test_explicit_power.PowerTorchTests.test_graph_torch_rule_manual_and_discriminating_inputs",
                      "test_explicit_power.PowerEvidenceTests.test_real_compiler_artifacts_references_correct_and_wrong_programs",
                      "test_explicit_power.PowerRuleEvidenceTests.test_two_rule_programs_independent_reference_and_cleanup"],
                      "explicit polynomial is the actual model; graph power(2/4) has manual/rule CPU evidence, wrong-exponent counterexamples and two first-pass live Agent cases in advanced_agent_evidence; not an automatic ReLU/SiLU replacement"),
    "linear": row("cpu_subset", ["test_fx_to_hecate.FXTranslatorTests.test_root_linear_functional_call",
                  "test_wide_linear.WideLinearRuleEvidenceTests.test_all_hidden_widths_real_encrypted_execution",
                  "test_wide_linear.WideLinearGoldenEvidenceTests.test_manual_and_wrong_neuron_through_isolated_candidate_path"],
                  "true packed input4 dot reduction; hidden scalar-neuron widths1..8, final output1..4; width5..8 two-layer fixtures verified, not arbitrary depth/packing"),
    "flatten": row("cpu_subset", ["test_model_graph.GraphTranslationTests.test_every_declared_graph_operator"],
                   "full C-row-major view only; not arbitrary batch/reshape/repacking"),
    "batch_norm": row("fixed_statistics_cpu_agent_subset", ["test_batch_norm.BatchNormTests.test_six_graphs_torch_reference_and_rule",
                      "test_batch_norm.BatchNormTests.test_invalid_parameters_fail_closed",
                      "test_batch_norm_evidence.BatchNormEvidenceTests.test_exact_models_sources_security_ciphertexts_and_counterexamples",
                      "test_batch_norm_paid.BatchNormPaidTests.test_six_real_generations_and_fixed_numeric_results",
                      "test_packed_composition.PackedCompositionTests",
                      "test_packed_composition_evidence.PackedCompositionEvidenceTests"],
                      "public fixed-statistics PyTorch N,C,... inference lowered to affine; legacy six-case manual/live evidence retained; schema5 rank2..4 <=256 elements, no-affine, negative/zero gamma, Conv and concat compositions have real rule/live evidence in packed_composition_evidence; upstream HE_BN packing closures remain unverified"),
    "conv": row("spatial_candidate_cpu_subset", ["test_spatial.SpatialTests.test_hand_calculated_cross_correlation_and_pool_divisor",
                "test_spatial.SpatialTorchTests.test_all_cases_reference_torch_rule_dsl",
                "test_spatial.SpatialEvidenceTests.test_all_goldens_and_wrong_windows_are_real_and_immutable",
                "test_grouped_spatial.GroupedSpatialTests.test_reject_invalid_groups_dilation_and_extra_fields",
                "test_grouped_spatial.GroupedSpatialTorchTests.test_reference_torch_exact_masks_rule_and_manual_programs",
                "test_grouped_spatial.GroupedSpatialEvidenceTests.test_six_goldens_two_counterexamples_actual_immutable_ckks",
                "test_grouped_spatial.GroupedSpatialRuleEvidenceTests.test_same_six_graphs_rule_pipeline_real_execution",
                "test_packed_spatial.PackedSpatialTests",
                "test_packed_spatial_evidence.PackedSpatialEvidenceTests"],
                "bounded Conv1D/2D cross-correlation; explicit stride/padding, grouped channels and dilation; legacy unbatched subset plus schema5 optional batch, <=256 total inputs/16 scalar outputs, rule and live Agent evidence in packed_spatial_evidence; upstream HE_Conv helpers remain unverified"),
    "pool": row("average_pool_candidate_cpu_subset", ["test_spatial.SpatialTests.test_hand_calculated_cross_correlation_and_pool_divisor",
                "test_spatial.SpatialTests.test_reject_wrong_channels_groups_dilation_stride_padding_and_overflow",
                "test_spatial.SpatialEvidenceTests.test_all_goldens_and_wrong_windows_are_real_and_immutable",
                "test_packed_spatial.PackedSpatialTests",
                "test_packed_spatial_evidence.PackedSpatialEvidenceTests"],
                "local AvgPool1D/2D floor mode, count_include_pad true/false; schema5 optional batch with <=256 total inputs/16 scalar outputs validated in packed_spatial_evidence; MaxPool and upstream helper closures remain unverified"),
    "zero_outputs": row("explicit_zero_abi_cpu_agent_subset", ["test_zero_abi.ZeroAbiTests.test_exact_declaration_and_no_logical_input_redefinition",
                        "test_zero_abi.ZeroAbiTests.test_legacy_contract_cannot_gain_zero_argument",
                        "test_zero_abi.ZeroTranslationTests.test_six_models_rule_manual_torch_and_independent_reference",
                        "test_zero_abi.ZeroEvidenceTests.test_real_ciphertexts_references_artifacts_counterexamples_and_cleanup",
                        "test_zero_abi.ZeroRuleEvidenceTests.test_rule_baseline_real_ciphertexts_independent_reference_and_key_cleanup",
                        "test_zero_abi.ZeroAgentEvidenceTests.test_seven_live_generations_reaudit_with_explicit_zero_input",
                        "test_spatial.SpatialEvidenceTests.test_exact_zero_elimination_repaired_actual_runtime"],
                        "versioned AST v4/request v5: 1..4 logical inputs plus one trusted public-key Enc(0); seven real CPU Agent cases and rule cases, six grouped goldens/three wrong programs plus a scalar-mask golden; no transparent-ciphertext exemption, bootstrap or change to user input/reference; arbitrary algebraic cancellation is not claimed supported"),
    "concat": row("static_concat_cpu_subset", ["test_concat.ConcatTests",
                  "test_concat_evidence.ConcatEvidenceTests",
                  "test_concat_paid.ConcatRuleTests",
                  "test_concat_paid.ConcatPaidTests",
                  "test_upstream_concat.UpstreamConcatTests",
                  "test_packed_composition.PackedCompositionTests",
                  "test_packed_composition_evidence.PackedCompositionEvidenceTests"],
                  "static C-order concat across matching non-axis dimensions, negative axes, 1..8 branches, rank1..4; legacy <=8 elements unchanged, schema5 <=16 scalar outputs with packed extraction/mixed layout and Conv/BN/Linear compositions verified in packed_composition_evidence; upstream HE_Concat local mask/carry fix has plaintext layout diagnostics only, not real einops/FHE/Agent helper validation"),
    "activation_approximation": row("explicit_error_decomposition_fixture_only",
                                   ["test_model_graph.GraphContractTests.test_reject_unsupported_ops_without_approximation",
                                    "test_approximation_errors.ApproximationTests.test_perfect_polynomial_execution_is_not_original_relu",
                                    "test_approximation_errors.ApproximationTests.test_wrong_implementation_and_signed_error_cancellation_are_visible",
                                    "test_approximation_errors.ApproximationEvidenceTests.test_two_real_candidates_and_three_independent_output_comparisons"],
                                    "Explicit illustrative ReLU/quadratic fixture separates approximation and execution residuals; automatic rewriting, upstream HE_ReLU/HE_SiLU and production approximation remain unverified and rejected"),
}

# Explicit typed-operand evidence remains separate from Agent generation coverage.
for _name in ('add', 'multiply', 'subtract', 'function_io', 'public_constant', 'broadcast'):
    SEMANTICS[_name]['tests'].extend([
        'test_broadcast_semantics.BroadcastContractTests.test_all_six_feature_partitions_are_live_in_manual_programs',
        'test_broadcast_semantics.BroadcastContractTests.test_bad_broadcast_and_mutating_aliases_rejected',
        'test_broadcast_semantics.BroadcastTorchTests.test_torch_translator_registry_and_manual_ast_have_independent_agreement',
        'test_broadcast_semantics.BroadcastEvidenceTests.test_five_goldens_five_counterexamples_real_fhe_immutable_reference_and_cleanup',
    ])
SEMANTICS['function_io']['tests'].append(
    'test_coverage_cohorts.CoverageCohortEvidenceTests.test_real_old96_new6_cpu_evidence_union')
for _name in ('broadcast', 'public_constant'):
    SEMANTICS[_name]['tests'].append(
        'test_semantic_guidance.SemanticGuidanceEvidenceTests.test_five_actual_guided_candidates_and_independent_plaintext_reference')

# A GPU primitive test does not establish the HEVM/DSL GPU execution contract.
for _name in ("add", "modswitch"):
    SEMANTICS[_name]["poseidon_gpu_primitive"] = "tc128_add_drop_prefix_fixture"
    SEMANTICS[_name]["poseidon_gpu_schedule"] = "explicit_physical_q_add_drop_fixture_not_hevm"
    SEMANTICS[_name]["tests"].extend([
        "test_gpu_modswitch_semantics.GpuModswitchEvidenceTests.test_native_execution_and_frozen_sources_logs",
        "test_gpu_modswitch_semantics.GpuModswitchEvidenceTests.test_tc128_all_valid_q_prefixes_aliases_negatives_and_decode",
        "test_gpu_drop_schedule.GpuDropScheduleEvidenceTests.test_frozen_sources_outputs_and_all_four_inputs_ten_transitions",
    ])

# Exact inventory of the pinned files' public operation families. Tests discover
# names from source AST/TableGen, so newly added upstream ops cannot silently vanish.
PYTHON_OPS = {"add": "add", "sub": "subtract", "mul": "multiply", "neg": "negate", "bootstrap": "bootstrap"}
EARTH_OPS = {"ConstantOp": "public_constant", "RotateOp": "rotation", "NegateOp": "negate",
             "BootstrapOp": "bootstrap", "RescaleOp": "rescale", "ModswitchOp": "modswitch",
             "UpscaleOp": "upscale", "ApplyScheduleOp": "schedule", "AddOp": "add", "MulOp": "multiply"}
CKKS_OPS = {"EncodeOp": "public_constant", "RotateCOp": "rotation", "NegateCOp": "negate",
            "RescaleCOp": "rescale", "ModswitchCOp": "modswitch", "UpscaleCOp": "upscale",
            "BootstrapCOp": "bootstrap", "AddCCOp": "add", "AddCPOp": "add",
            "MulCCOp": "multiply", "MulCPOp": "multiply"}
POLY_HELPERS = {"HE_BN": "batch_norm", "HE_MPBN": "batch_norm", "HE_Conv": "conv", "HE_ConvBN": "conv",
                "HE_MaxPad": "pool", "HE_Max": "pool", "HE_Avg": "pool", "HE_DS": "pool", "HE_Pool": "pool",
                "HE_Linear": "linear", "HE_ReshapeLinear": "flatten", "HE_DwConv": "conv", "HE_Concat": "concat",
                "HE_ReLU": "activation_approximation", "HE_SiLU": "activation_approximation"}
# These are source presence mappings, NOT permission to call the poly helpers:
POLY_HELPER_EXECUTION = "none_verified_or_allowed_in_generated_programs"


def inventory():
    from model_graph import OPS
    from expanded_model_suite import FAMILIES, VERSION
    return dict(dacapo_commit=DACAPO_COMMIT, semantics=SEMANTICS,
                native_packed_evidence=dict(
                    request_task='hecate-periodic-packed-native-synthesis-v1',model_schema=5,
                    execution_abi='periodic-packed-v1',logical_rank=[1,4],logical_elements=[1,256],
                    tested_periods=[8,16,32,64,128,256],output_ciphertexts_limit=16,
                    native_v7_composed_with_packed=True,old_contracts_unchanged=True,
                    report=str(RESULTS / 'packed-native-goldens-nv5t6iva/report.json'),
                    sha256='a7ac662dd85eb2ecb7043d1a5f0cd7b4d63d81023a8260e6e81efa20e69c977d',
                    correct_programs=6,correct_passed=6,wrong_alias_or_order_rejected=2,
                    live_report=str(RESULTS / 'agent-batch-aqu_6yng/report.json'),
                    live_sha256='f1bcbbf4d29e669292f005a04e3c5f1ce72f2c47a88d31db3d71db58888391b7',
                    live_first_passes=3,live_final_passes=6,live_api_calls=10,live_repairs=4,
                    live_transport_retries=0,live_reported_tokens=155955,
                    live_helper_programs=2,live_recorded_helper_calls=22,
                    live_array_or_loop_or_augmented_or_starred_programs=0,
                    all_native_constructs_live_covered=False,live_input_executions=24,live_compared_values=760,
                    audit=str(RESULTS / 'agent-lineage-audit-tgqcgcvo/report.json'),
                    security_or_tolerance_changed=False,arbitrary_shapes_supported=False,
                    poseidon_gpu_validated=False,full_semantics_proven=False),
                node_layout_guidance_evidence=dict(
                    guidance_schema=2,revision='node-layout-v1',model_schema=5,
                    old_guidance_preserved=True,ast_and_abi_unchanged=True,
                    old_failure_retests=2,new_compositions=4,
                    report=str(RESULTS / 'layout-guidance-goldens-xn_25n73/report.json'),
                    sha256='7a941d16497ce4539076adf5eb55685160af6605950a8df8f065f0454029402e',
                    correct_programs=6,correct_passed=6,
                    live_report=str(RESULTS / 'agent-batch-cij14tb3/report.json'),
                    live_sha256='1dc8abc94e6caee2067c06a2f0bd9de6120439b985cf04bbcd99601b0de46547',
                    live_first_passes=6,live_final_passes=6,live_api_calls=6,
                    live_repairs=0,live_transport_retries=0,live_reported_tokens=249205,
                    input_executions_successful=24,compared_values_successful=512,
                    audit=str(RESULTS / 'agent-lineage-audit-d7sw8s1d/report.json'),
                    historical_rates_rewritten=False,statistically_proven_improvement=False,
                    poseidon_gpu_validated=False,full_semantics_proven=False),
                tensor_permutation_evidence=dict(
                    model_schema=5,execution_abi='periodic-packed-v1',logical_rank=[1,4],elements_limit=256,
                    packed_rotation_and_destination_masks=True,scalar_neuron_reference_reordering=True,
                    transpose_is_not_reshape=True,original_reference_independent_of_lowering=True,
                    report=str(RESULTS / 'tensor-permutation-goldens-mzox_ovk/report.json'),
                    sha256='6eb796008ce3a82f1357a4a74215c42f0d44ad7beaad2416cb5935b02a5a1059',
                    correct_programs=12,correct_passed=12,wrong_rotation_or_order_rejected=2,
                    live_report=str(RESULTS / 'agent-batch-ks9rbv17/report.json'),
                    live_sha256='5e8a22652c0f69f4e5bd260beab9102d2f2e2bc629b4beb1ff05b404dc6fc3a5',
                    live_first_passes=10,live_final_passes=12,live_api_calls=15,live_reported_tokens=581018,
                    live_repairs=3,live_transport_retries=0,input_executions_successful=48,
                    input_executions_including_failures=60,compared_values_successful=1816,
                    initial_failure_layers={'numerical_comparison':2},failed_attempts=3,
                    audit=str(RESULTS / 'agent-lineage-audit-gtkar04j/report.json'),
                    counted_as_new_upstream_dsl_primitive=False,security_or_tolerance_changed=False,
                    poseidon_gpu_validated=False,arbitrary_shape_supported=False,full_semantics_proven=False),
                packed_composition_evidence=dict(
                    model_schema=5,execution_abi='periodic-packed-v1',bn_rank=[2,4],bn_elements_limit=256,
                    concat_rank=[1,4],concat_scalar_output_limit=16,concat_mixed_layout_supported=True,
                    public_fixed_statistics_only=True,original_reference_independent_of_lowering=True,
                    report=str(RESULTS / 'packed-composition-goldens-4jn3zxd_/report.json'),
                    sha256='3f7e421fcb727076baaf2c2af4f66bd8d886acce575d6bfccf432780e3b4d1af',
                    correct_programs=12,correct_passed=12,wrong_coefficients_or_order_rejected=2,
                    live_report=str(RESULTS / 'agent-batch-j0cqw9mk/report.json'),
                    live_sha256='0ab6ba6f2f292f872ef2f3d4bd8574324661d5d96b6f7e6ded9ce4f82521f429',
                    live_first_passes=12,live_final_passes=12,live_api_calls=12,live_reported_tokens=181425,
                    live_repairs=0,live_transport_retries=0,input_executions=48,compared_values=2228,
                    audit=str(RESULTS / 'agent-lineage-audit-tzp3quj8/report.json'),
                    security_or_tolerance_changed=False,poseidon_gpu_validated=False,
                    upstream_poly_helpers_allowed=False,arbitrary_shape_supported=False,full_semantics_proven=False),
                packed_spatial_evidence=dict(
                    model_schema=5,execution_abi='periodic-packed-v1',input_elements_limit=256,
                    scalar_neuron_total_limit=16,optional_leading_batch=True,
                    grouped_dilated_conv=True,average_pool_include_exclude_padding=True,
                    original_window_reference_independent_of_lowering=True,
                    reports=[dict(path=str(RESULTS / 'packed-spatial-goldens-hcvi8_gd/report.json'),
                                  sha256='1eaa22ae87e00d406c0cb5e270cecdf289b6ac6c0035e6a9a68c8a56570bf8e7'),
                             dict(path=str(RESULTS / 'packed-spatial-max-goldens-9nu5sl9n/report.json'),
                                  sha256='84e298173a10c16558867ad18c335f290cab858fed601e4cb28ee2d0da0594c0')],
                    correct_programs=16,correct_passed=16,wrong_group_or_window_rejected=2,
                    live_report=str(RESULTS / 'agent-batch-x47lnr8p/report.json'),
                    live_sha256='ed8515adc7a7f16be623460a7b304ba8c9dce178ead220881dd59b80ff95aeba',
                    live_first_passes=16,live_final_passes=16,live_api_calls=16,live_reported_tokens=251130,
                    live_repairs=0,live_transport_retries=0,input_executions=64,compared_values=576,
                    audit=str(RESULTS / 'agent-lineage-audit-lr3sx5l2/report.json'),
                    security_or_tolerance_changed=False,poseidon_gpu_validated=False,
                    upstream_poly_helpers_allowed=False,arbitrary_shape_supported=False,full_semantics_proven=False),
                tensor_input_evidence=dict(
                    model_schema=5,execution_abi='periodic-packed-v1',logical_rank=[1,4],
                    row_major_shape_preserved=True,plaintext_trailing_axis_broadcast=True,
                    reshape_single_inferred_dimension=True,linear_applies_to_last_axis=True,
                    reference_uses_independent_indexing_not_lowering=True,
                    packed_output_elements_limit=256,scalar_neuron_total_limit=16,
                    report=str(RESULTS / 'tensor-model-goldens-3pf44dof/report.json'),
                    sha256='b34d6ba134a251abaaf9fbea8fc9773effde6e74eeec37f316782c5ddb89c5b7',
                    correct_programs=12,correct_passed=12,wrong_reduction_or_group_rejected=2,
                    live_report=str(RESULTS / 'agent-batch-e7vjdf2m/report.json'),
                    live_sha256='aa2780ae3db57b983564be4ef13322596716262efd6162bc9285d68ac9736d5f',
                    live_first_passes=12,live_final_passes=12,live_api_calls=12,live_reported_tokens=148203,
                    live_repairs=0,live_transport_retries=0,input_executions=48,compared_values=1012,
                    audit=str(RESULTS / 'agent-lineage-audit-iwc9qo13/report.json'),
                    security_or_tolerance_changed=False,poseidon_gpu_validated=False,
                    ciphertext_shape_expanding_broadcast=False,arbitrary_shape_supported=False,
                    full_semantics_proven=False),
                periodic_packed_input_evidence=dict(
                    model_schema=5,request_task='hecate-periodic-packed-synthesis-v1',
                    execution_abi='periodic-packed-v1',logical_elements=[1,256],logical_rank=[1,4],
                    physical_model_ciphertexts=1,slot_periods=[4,8,16,32,64,128,256],
                    scalar_neuron_output_limit=16,packed_prefix_output_limit=256,
                    report=str(RESULTS / 'packed-model-goldens-ibny_ihk/report.json'),
                    sha256='ed7a8282f4c39a439ed9dabcf016465d02ca22bd0c7d759a6450b74eded003a1',
                    generator='deterministic_packed_fx',correct_programs=12,correct_passed=12,
                    wrong_reduction_counterexamples_rejected=2,input_executions=48,compared_values=1208,
                    live_agent_validated=True,
                    live_report=str(RESULTS / 'agent-batch-h98vtawd/report.json'),
                    live_sha256='f532bc6060086e4681083acc3d5e276b014a1e7b54d2d44f1acaef95b4889f98',
                    live_cases=12,live_first_passes=12,live_final_passes=12,live_api_calls=12,
                    live_repairs=0,live_transport_retries=0,live_reported_tokens=166413,
                    compiler_configuration='seal-cpu-eva-w45-v1',security_profile_changed=False,
                    default_configuration_changed=False,old_schema_behavior_unchanged=True,
                    native_construction_combined_with_packed_abi_validated=False,
                    native_composition_followup='native_packed_evidence',
                    poseidon_gpu_validated=False,all_shape_sizes_supported=False,full_semantics_proven=False),
                chunked_input_evidence=dict(
                    model_schema=4, request_task='hecate-chunked-input-synthesis-v1',
                    logical_elements=[5,16], logical_rank=[1,4], physical_ciphertexts=[2,4],
                    period_per_ciphertext=4, hidden_width_limit=8, output_elements=[1,4],
                    report=str(RESULTS / 'chunked-model-goldens-cs9wkfzq/report.json'),
                    sha256='cad12cea82cb2af52df21c8ae14950d3f6c1d1de010a5b4e1fb81d4016b2ef8a',
                    generator='deterministic_chunked_fx', correct_programs=10, correct_passed=10,
                    wrong_chunk_counterexamples_rejected=2, input_executions=40, compared_values=80,
                    original_logical_reference_independent=True, old_schema_behavior_unchanged=True,
                    compiler_configuration='seal-cpu-eva-w45-v1', default_configuration_changed=False,
                    agent_calls=0, live_agent_validated=True, all_shape_sizes_supported=False,
                    live_report=str(RESULTS / 'agent-batch-zea03xuw/report.json'),
                    live_sha256='2a5c01df5e3ee59ee9da4a0eedb181fc78ae2fcda41d68b0cc608c2a1b0ed46a',
                    live_cases=10, live_first_passes=7, live_final_passes=10, live_api_calls=14,
                    original_default_route_failure_preserved=True,
                    binding_fix_original_candidate_replay_report=str(RESULTS / 'chunked-trace-replays-loh3_99e/report.json'),
                    binding_fix_replay_sha256='22590899b7d0f3582840cad4f302874170ccb8763c77b29d5d6d23e9e889d378',
                    full_semantics_proven=False),
                compiler_configuration_evidence=dict(
                    configurations=['seal-cpu-eva-w40-v1','seal-cpu-eva-w45-v1'],
                    report=str(RESULTS / 'native-loop-config45-goldens-tu_39c3f/report.json'),
                    sha256='922c8fa5aea23d2ee940c2624c1211b753d46fb7fe3cd64dc6721931c58485be',
                    guard_report=str(RESULTS / 'compiler-configuration-guard-qv2ptpog/report.json'),
                    guard_sha256='260c8979ecc3824798f90d3dc65e60d0a67c81a083571aadb19547b5d4af467e',
                    explicit45_correct_programs=8, explicit45_correct_passed=8,
                    wrong_bound_rejected=1, real_worker_configuration_rejections=3,
                    positive_compared_values=128, agent_calls=0, default_waterline=40,
                    default_profile_changed=False, original_failure_preserved=True,
                    legacy_request_identity_preserved=True, named_profile_live_agent_validated=False,
                    full_semantics_proven=False),
                hevm_graph_precision_evidence=dict(
                    report=str(RESULTS / 'hevm-graph-precision-glskuy3w/report.json'),
                    sha256='78ca3fd3faba35c64ee3755973f815280d20fa3e6dd9a547310e1192864caff0',
                    waterlines=[40,45], matched_key_sets=3, model_programs=8,
                    compiled_artifacts=16, program_executions=48, passed_program_executions=48,
                    input_executions=192, compared_values=576, agent_calls=0,
                    semantic_hevm_instructions_identical=False, actual_runtime_scales_verified=True,
                    original_failure_preserved=True, production_waterline=40,
                    production_profile_changed=False, threshold_changed=False,
                    finite_broader_graph_precision_verified=True, stable_all_input_precision_proven=False),
                hevm_waterline_precision_evidence=dict(
                    report=str(RESULTS / 'hevm-waterline-diagnostic-ds51hu27/report.json'),
                    sha256='142e95ac072b8b539c6e313365fc21a9452d73d04ad1834481bc381410cd89b4',
                    waterlines=[40,45,50], matched_key_sets=3, model_programs=1,
                    input_executions=36, compared_values=144, agent_calls=0,
                    semantic_hevm_instructions_identical=True, actual_runtime_scales_verified=True,
                    original_failure_preserved=True, production_waterline=40,
                    production_profile_changed=False, threshold_changed=False,
                    broader_graph_precision_verified=False, stable_all_input_precision_proven=False),
                native_public_loop_evidence=dict(
                    request_task='hecate-native-function-synthesis-v7',
                    report=str(RESULTS / 'native-loop-goldens-z4ul_cpj/report.json'),
                    sha256='a9c002c6901ca4e8bbfa1b2dbf2fec215a657fcb6f84c027989073db81cb2915',
                    batch_status='failed', correct_programs_tested=8, correct_programs_passed=7,
                    correct_program_numerical_failures=1, detected_wrong_bound_counterexamples=1,
                    positive_input_executions=32, positive_compared_values=128,
                    agent_calls=0, encrypted_control_flow=False,
                    live_agent_validated=False, all_goldens_passed=False, full_semantics_proven=False),
                rotation_precision_diagnostic=dict(
                    report=str(RESULTS / 'seal-rotation-precision-eqqq7v6t/report.json'),
                    sha256='335be08ee55f82c4221d006ed0465fb775714cabe0ed7d6f31104f0141abef11',
                    native_stage_observations=72, key_sets=2, input_vectors_per_key=3,
                    original_failed_key_reproduced=False, production_profile_changed=False,
                    threshold_changed=False, stable_precision_budget_verified=False),
                native_array_arithmetic_evidence=dict(
                    request_task='hecate-native-function-synthesis-v6',
                    report=str(RESULTS / 'native-array-arithmetic-goldens-l742dym9/report.json'),
                    sha256='9de9d7a55ca6223eab7d4a7c752e9fc90d95a446ed13cce72ee5431d9e6cf7cd',
                    manual_cases=8, detected_broadcast_counterexamples=1,
                    input_executions=32, compared_values=128, agent_calls=0,
                    outer_expr_array_broadcast=True, packed_slot_broadcast=False,
                    zero_dim_result_is_expr=True, scalar_left_array_rejected=True,
                    live_agent_validated=False, full_semantics_proven=False),
                native_array_mutation_evidence=dict(
                    request_task='hecate-native-function-synthesis-v10',
                    report=str(RESULTS / 'native-array-mutation-goldens-c9d3npba/report.json'),
                    sha256='402c93fe919c083f8e625f842e22398f1c7f77b4a5c4af6a44c676798c468a77',
                    layout_report=str(RESULTS / 'native-array-layout-goldens-c52z6uhz/report.json'),
                    layout_sha256='0e52aa102a5fc8a7c9dce0859a7eb669bd8ca25ae836ce07bcc323a36f3215b1',
                    compiler_configuration='seal-cpu-eva-w45-v1',
                    manual_cases=13, detected_counterexamples=2,
                    input_executions=52, compared_values=208, agent_calls=0,
                    typed_alias_heap=True, actual_alias_cell_observations=True, keep_order_layout=True,
                    python_class_is_ir_type=False, subscript_writes_enabled=False,
                    live_agent_validated=False, full_semantics_proven=False),
                native_scalar_augmented_evidence=dict(
                    request_task='hecate-native-function-synthesis-v9',
                    report=str(RESULTS / 'native-augmented-goldens-4_7ws610/report.json'),
                    sha256='86a35b5452cc88221b302610109cb34193b8d33d1d705041361e1bd457c33474',
                    compiler_configuration='seal-cpu-eva-w45-v1',
                    manual_cases=7, detected_counterexamples=2,
                    input_executions=28, compared_values=112, agent_calls=0,
                    actual_augmented_dispatch=True, unchanged_expr_aliases=True,
                    array_inplace_mutation_enabled=False, live_agent_validated=False,
                    full_semantics_proven=False),
                native_star_construction_evidence=dict(
                    request_task='hecate-native-function-synthesis-v8',
                    report=str(RESULTS / 'native-star-exercise-goldens-a7vok9vv/report.json'),
                    sha256='cd7cb791622e05717ee4f5658d13ea60c4ec9584f99d7abf70d24ad0905b5d41',
                    audit=str(RESULTS / 'native-star-exercise-audit-k3k8atoy/report.json'),
                    audit_sha256='87eced0da4a4c96c7376075a8ecafe7eeba424e3240e35973aa6d2051386e4be',
                    catalog='scripts/baseline/native_star_exercises.py',
                    catalog_sha256='841646f34d9c7052e4dc227e3b286200c484aaafaac1628590ca95932879af90',
                    compiler_configuration='seal-cpu-eva-w45-v1',
                    manual_cases=8, detected_counterexamples=1, unique_features=9,
                    finite_argument_influence_features=8, structural_features=1,
                    input_executions=32, compared_values=128, live_agent_cases=0,
                    actual_frontend_expansion_observation=True, full_semantics_proven=False),
                native_starred_argument_evidence=dict(
                    request_task='hecate-native-function-synthesis-v5',
                    report=str(RESULTS / 'native-starred-goldens-9hghp1ci/report.json'),
                    sha256='3cd723b2c20a3e3d664427dda5b8a1796eb5105625917266478e7aaee88eb12a',
                    manual_cases=8, detected_order_counterexamples=1,
                    input_executions=32, compared_values=128, agent_calls=0,
                    upstream_scalar_abi_unchanged=True, first_axis_iteration=True,
                    implicit_flattening=False, expr_array_as_one_native_argument=False,
                    live_agent_validated=False, full_semantics_proven=False),
                native_array_construction_evidence=dict(
                    request_task='hecate-native-function-synthesis-v4',
                    report=str(RESULTS / 'native-array-exercise-goldens-qcummop0/report.json'),
                    sha256='e3afbd9f89179c7a15436aa77db2d7828aded29bebfbf8a4b12a1a89ad4ee274',
                    audit=str(RESULTS / 'native-array-exercise-audit-cf9u_u66/report.json'),
                    audit_sha256='68a23c574fe9f9c6c6a0681c1b0f37a0681307f13eb13ba615ff387b3eedf4df',
                    catalog='scripts/baseline/native_array_exercises.py',
                    catalog_sha256='a7462ea3ff92dfc864bb3c4c16c63f836ff21a40809da131d861dd9c74a6f81a',
                    manual_cases=10, detected_counterexamples=1, unique_features=14,
                    finite_cell_influence_features=13, structural_features=1,
                    input_executions=40, compared_values=160, live_agent_cases=0,
                    actual_frontend_storage_observation=True, full_semantics_proven=False),
                native_function_agent_evidence=dict(
                    report=str(RESULTS / 'agent-batch-bg4htr49/report.json'),
                    sha256='9cbe3a0f9a1ad2904a6c669df5f0f865505be74084f84d88df667f5f13ff7f30',
                    audit=str(RESULTS / 'native-exercise-audit-s9vhta5d/report.json'),
                    audit_sha256='7279990dcc5364b3d0d7b3d83b723b3e71924a049255b8645d58ca526d026c52',
                    cases=11, first_successes=10, feature_count=11,
                    output_influence_features=10, trace_structural_features=1,
                    input_executions=44, compared_values=176, api_calls=12,
                    transport_retries=0, reported_tokens=96984,
                    model='deepseek-flash', reasoning_effort='high',
                    api_concurrency=10, native_execution_concurrency=2,
                    native_array_live_agent_validated=False, full_semantics_proven=False),
                current_goal_scope=dict(execution_backend="upstream_SEAL_HEVM_CPU",
                    poseidon_gpu_required=False,
                    note="User removed GPU integration from the active Agent-correctness scope on 2026-09-11; historical GPU evidence is retained."),
                grammar_coverage=dict(tool="scripts/baseline/audit_dsl_coverage.py",
                    tests="test_dsl_grammar_coverage",
                    report=str(RESULTS / "dsl-grammar-audit-xs_s4cxq/report.json"),
                    sha256="953a5c1acd43c286cb2db6e949c0357db66ac3e29a6f6e673aa7e195da1de0b6",
                    agent_observed_feature_partitions=29, feature_partition_count=32,
                    observation="29 of 32 structural partitions in the re-audited 96+6+5+7+12 Agent evidence union; cohorts remain separate, not full semantic coverage"),
                agent_semantic_guidance=dict(schema=1, source='candidate_contract.SEMANTIC_GUIDANCE',
                    hash_bound=True, legacy_requests_unchanged=True, expands_grammar=False,
                    tests=['test_semantic_guidance.SemanticGuidanceTests',
                           'test_semantic_guidance.SemanticGuidanceEvidenceTests'],
                    live_report=str(RESULTS / 'agent-lineage-audit-q24oeyp0/report.json'),
                    live_report_sha256='eba491ec609efb3933c1d7dee39e1e1dd68a89f32d52e0fe92777a1cec105221'),
                manual_broadcast_evidence=dict(
                    report=str(RESULTS / "broadcast-golden-batch-cq9e4lbd/report.json"),
                    sha256="55068edbd93b9f632a335d1307191a7be3cc0a86256b1db7f326efeb33730465",
                    features=['statement.alias', 'add.length1', 'multiply.length1',
                              'subtract.scalar', 'subtract.length1', 'subtract.length4'],
                    golden_passes=5, correctly_rejected_after_real_execution=5, agent_calls=0,
                    test='test_broadcast_semantics.BroadcastEvidenceTests.test_five_goldens_five_counterexamples_real_fhe_immutable_reference_and_cleanup'),
                manual_semantic_audit=dict(
                    tool='scripts/baseline/audit_manual_semantics.py',
                    report=str(RESULTS / 'manual-semantics-audit-i_brftfr/report.json'),
                    sha256='ade92ae69b5cf9e026625ca517fa68787ed8082fa55911fa578e194c2469ed5b',
                    audited_programs=61, correct_goldens=42, detected_counterexamples=19,
                    input_batches=244, compared_values=716, observed_graph_operators=13,
                    original_input_reference_recomputed=True, actual_decrypted_arrays_recomputed=True,
                    compiled_artifacts_reparsed=True, legacy_v1_key_probe_missing=3,
                    tests=['test_manual_semantics.RecomputedArrayTests',
                           'test_manual_semantics.ManualAuditEvidenceTests'],
                    new_fhe_executions=0, new_agent_calls=0, full_semantics_proof=False),
                encrypted_zero_evidence=dict(
                    golden_report=str(RESULTS / 'zero-golden-batch-w9vuz53i/report.json'),
                    golden_sha256='28a6332e9db74732819707deafa5acd75edf4b142f1a30c74e2f834b4f84b96a',
                    rule_report=str(RESULTS / 'fx-batch-nmqzon3l/report.json'),
                    rule_sha256='354b55058e12f329d787ba056bab520ec21ea696e3398453e67b9e418ff32e3d',
                    agent_report=str(RESULTS / 'agent-batch-gp73w2a1/report.json'),
                    agent_sha256='7a56d87021642885ef317550ab09299854b9f320a5cdd98f12a74816bda85c33',
                    agent_cases=7, agent_first_successes=7, logical_inputs_unchanged=True,
                    auxiliary_input='trusted_client_public_key_encrypted_zero',
                    full_algebraic_cancellation_supported=False),
                explicit_power_evidence=dict(
                    golden_report=str(RESULTS / 'explicit-power-goldens-a3ovzyp7/report.json'),
                    golden_sha256='58cee079ef167d56eed5f75ec96f7396e4bb89554608e2317478f2a13e45b9bd',
                    rule_report=str(RESULTS / 'fx-batch-e_r7dpt6/report.json'),
                    rule_sha256='47291c774a352958b9030f71e75bef59ce50ec24b25424b30c0cad7bc18aa152',
                    correct_goldens=2, wrong_exponents_rejected=2, live_agent_validated=True,
                    live_report=str(RESULTS / 'agent-batch-0j5c90hj/report.json'),
                    live_cases=['explicit-power-2', 'explicit-power-4']),
                advanced_agent_evidence=dict(
                    report=str(RESULTS / 'agent-batch-0j5c90hj/report.json'),
                    sha256='c4056e98ba730dbccdd23f43f926cc7bfde29bdd672c1fda4a4a45334d266297',
                    manifest='scripts/baseline/cases/advanced-agent-12-manifest.json',
                    manifest_sha256='a398e1ec1ade2d1639d793b41cf8fe8523df4cb3a8b0c901b0b0e869cb4d5678',
                    cases=12, first_successes=12, input_executions=48, compared_values=124,
                    api_calls=12, repairs=0, service_provider='deepseek', model='deepseek-flash',
                    api_concurrency=10, native_execution_concurrency=2,
                    tests=['test_advanced_agent_manifest.AdvancedTwelveEvidenceTests',
                           'test_advanced_agent_manifest.CompletedCapabilityEvidenceTests']),
                model_capability_evidence=dict(
                    tool='scripts/baseline/audit_model_capabilities.py',
                    report=str(RESULTS / 'model-capability-audit-58yddwhv/report.json'),
                    sha256='234af9a8e98d6f19ce1e297c8d586df75427e6877cab2577794ee62f2a28e1a9', total_agent_cases=126,
                    user_graph_cases=78, legacy_catalog_cases=48,
                    output_reachable_graph_operators=13, supported_graph_operators=13,
                    missing_live_graph_operators=[],
                    historical_114_case_report=str(RESULTS / 'model-capability-audit-zxrvrtlh/report.json'),
                    test='test_advanced_agent_manifest.CompletedCapabilityEvidenceTests.test_recomputed_126_cases_all_13_graph_operators_and_historical_split'),
                python_ops=PYTHON_OPS, earth_ops=EARTH_OPS, ckks_ops=CKKS_OPS, poly_helpers=POLY_HELPERS,
                baseline_counts=BASELINE_COUNTS, target_counts=TARGET_COUNTS,
                current_graph_operators=sorted(OPS), current_graph_operator_count=len(OPS),
                self_contained_model_suite=dict(version='user-graph-suite-v2', cases=96, model_families=16,
                    manifest='scripts/baseline/cases/user-graph-suite-v2.json',
                    manifest_sha256='1486b3025542a8d4c625287408ba6f9049d38edbdc69e2a3dadd4e96cf55bc68',
                    provenance='scripts/baseline/cases/user-graph-suite-v2.provenance.json',
                    provenance_sha256='b8c3e34ffc05b3adf0c138e9c4ab8acc9cf57f4b93adbb07c8bed3db15bc8c9e',
                    catalog_lookup_required=False, historical_agent_reports_reclassified=False,
                    new_96_case_live_agent_cohort_validated=False,
                    migrated_rule_report=str(RESULTS / 'fx-batch-t0alnl8z/report.json'),
                    migrated_rule_sha256='868bebe4148a12cb8e6467867692ae52302883c21f90098283520e52fb6cc6a4',
                    migrated_rule_cases=48, migrated_rule_agent_calls=0,
                    tests=['test_catalog_graph_migration.CatalogMigrationTorchTests',
                           'test_catalog_graph_migration.CatalogMigrationEvidenceTests']),
                current_catalog_model_families=8,
                expanded_benchmark_model_families=len(FAMILIES),
                expanded_benchmark_version=VERSION,
                expanded_benchmark_tests=["test_expanded_suite.ExpandedEvidenceTests.test_exact_96_descriptors_and_families_have_real_execution"],
                expanded_benchmark_live_agent_validated=True,
                expanded_benchmark_live_agent_validation_scope="cumulative_heterogeneous_cpu_96_cases_16_families",
                single_configuration_cohort_passed=False,
                live_agent_evidence=dict(
                    report=str(RESULTS / "agent-lineage-audit-73raxsas/report.json"),
                    sha256="05f3f8b8e3e2d1bfff1b6d7595e711ac68818189a606d42dad5980f3bbb272aa",
                    tests=["test_agent_lineage_audit.RealLineageEvidenceTests.test_saved_outputs_artifacts_and_cumulative_coverage"],
                    note="Historical evidence re-audited from saved arrays/artifacts; not a fresh or homogeneous 96-case run."),
                all_semantics_verified=False, all_goal_requirements_complete=False,
                poly_helper_execution=POLY_HELPER_EXECUTION)


if __name__ == "__main__":
    import json
    print(json.dumps(inventory(), indent=2))
